[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "B", "UP"]
target-version = "py312"

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true
warn_return_any = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra --strict-markers"
minversion = "7.0"
